[package]
name = "gst-rust"
version = "0.1.0"
authors = ["Bo Du <bokwandu@gmail.com>"]

[dependencies]
clap = "2.31.2"
url = "1.7.0"
openssl = "0.9"
rand = "0.4.2"
gstreamer = "0.11.1"

[dependencies.ws]
version = "0.7.6"
features = ["ssl"]
